# .golangci.yml
# Configuration file for golangci-lint

# Options for analysis running
run:
  # Default concurrency is a available CPU number
  concurrency: 4
  # Timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 5m

# List of linters to run
linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - revive        # Modern replacement for golint
    - misspell
    - gosec
    - bodyclose
    - gocritic

# Linter settings
linters-settings:
  revive: # Configuration for revive (replacement for golint)
    rules:
      - name: exported
        arguments:
          - "checkPrivateReceivers"
          - "disableStutteringCheck"
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  gosec:
    excludes:
      - G204  # Subprocess launching with variable (consider if this is appropriate)

# Issues configuration
issues:
  # Maximum issues count per one linter
  max-issues-per-linter: 0
  # Maximum count of issues with the same text
  max-same-issues: 0
  # Show only new issues
  new: false
  # Exclude specific issues by regular expression
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - dupl