# .golangci.yml - Simplified configuration compatible with v1.64
run:
  concurrency: 4
  timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - revive
    - misspell

# Minimal linter settings to avoid validation errors
linters-settings:
  revive:
    rules:
      - name: exported
  govet:
    # Settings have changed in v1.64
    check-shadowing: false # Removed this setting as it's not valid
    enable-all: true
    disable:
      - shadow # Enable shadow checking explicitly this way instead
  misspell:
    locale: US